name = "FileCheck"
uuid = "4e644321-382b-4b05-b0b6-5d23c3d944fb"
version = "1.1.2"
authors = ["Tim Besard <tim.besard@gmail.com>"]

[deps]
LLVM_utils_unified_jll = "0def2053-1a45-54bc-bfc1-6427e7aae702"

[compat]
LLVM_utils_unified_jll = "0.1.0"
julia = "1.10"
